# Generated by Django 5.0.3 on 2024-03-12 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pol", "Politics"),
                            ("art", "Art"),
                            ("tech", "Technology"),
                            ("trivia", "Trivia"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("uk", "United Kingdom"),
                            ("eu", "Europe"),
                            ("w", "World"),
                        ],
                        max_length=10,
                    ),
                ),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("details", models.CharField(max_length=128)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="newsapi.author"
                    ),
                ),
            ],
        ),
    ]
