# Generated by Django 5.0.3 on 2024-03-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsapi", "0002_newsstory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsstory",
            name="pub_date",
            field=models.DateField(verbose_name="Date published"),
        ),
    ]
